name       : ledger
version    : 3.1.1
release    : 5
source     :
    - https://github.com/ledger/ledger/archive/v3.1.1.tar.gz : 90f06561ab692b192d46d67bc106158da9c6c6813cc3848b503243a9dfd8548a
license    : BSD-3-Clause
component  : office.finance
summary    : A double-entry UNIX command-line accounting system
description: |
    Ledger is a powerful, double-entry accounting system that is accessed from the UNIX command-line.
builddeps  :
    - libboost-devel
setup      : |
    %patch -p1 < $pkgfiles/boost161.patch
    %cmake -DUSE_PYTHON=on .
build      : |
    %make
install    : |
    %make_install
