name       : ledger
version    : 3.1.3
release    : 7
source     :
    - https://github.com/ledger/ledger/archive/v3.1.3.tar.gz : b248c91d65c7a101b9d6226025f2b4bf3dabe94c0c49ab6d51ce84a22a39622b
license    : BSD-3-Clause
component  : office.finance
summary    : A double-entry UNIX command-line accounting system
description: |
    Ledger is a powerful, double-entry accounting system that is accessed from the UNIX command-line.
builddeps  :
    - libboost-devel
setup      : |
    %cmake -DUSE_PYTHON=on .
build      : |
    %make
install    : |
    %make_install
